# Frontend Dockerfile for NemoClaw-agritwin-dairy-agentic-ai-platform-frontend
# Generated by AgriTwin Agent Factory

FROM node:20-alpine

WORKDIR /app

COPY package.json .
RUN npm install --production

COPY . .

EXPOSE 8080

CMD ["node", "runtime-server.mjs"]
