// runtime-server.mjs — generated by AgriTwin Agent Factory
// Long-running HTTP wrapper that keeps the container alive.

import http from 'node:http';
import { createServer } from 'node:http';
import fs from 'node:fs';

let app = null;
let loaded = false;
let loadError = null;

try {
  const mod = await import('./src/index.mjs');
  app = mod.default || mod.app || mod;
  loaded = true;
} catch (err) {
  loadError = err.message;
  console.error('[runtime-server] Failed to load app module:', err.message);
}

const server = createServer((req, res) => {
  const url = req.url.split('?')[0];
  const method = req.method;

  if (url === '/health' || url === '/ready') {
    const status = loaded ? 200 : 503;
    res.writeHead(status, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: loaded ? 'healthy' : 'unhealthy',
      loaded,
      error: loadError || null,
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-frontend',
      type: 'frontend',
    }));
    return;
  }

  if (url === '/' || url === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(`<!DOCTYPE html>
<html>
<head>
  <title>AGRI-OS</title>
  <style>
    body {
      font-family: JetBrains Mono, monospace;
      background-color: #0D1117;
      color: #39D353;
      margin: 0;
      padding: 20px;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      flex: 1;
    }
    header {
      background-color: #0D1117;
      padding: 1rem;
      border-bottom: 1px solid #39D353;
    }
    .component-list {
      margin: 1rem 0;
    }
    .component-item {
      padding: 0.5rem;
      margin: 0.25rem 0;
      background-color: #161B22;
      border-radius: 4px;
    }
    .status-indicator {
      color: #39D353;
      font-weight: bold;
    }
  </style>
</head>
<body>
  <header>
    <h1>AGRI-OS - Dark Industrial Operations (Mission Control)</h1>
    <div class="status-indicator">System Operational</div>
  </header>
  <div class="container">
    <h2>Farm Status Overview</h2>
    <div class="component-list">
      <h3>Active Components:</h3>
      <div class="component-item">1</div>
      <div class="component-item">2</div>
      <div class="component-item">3</div>
      <div class="component-item">4</div>
      <div class="component-item">FieldZoneMap</div>
      <div class="component-item">AgentActivityFeed</div>
      <div class="component-item">FarmStatusOverview</div>
      <div class="component-item">BottomTabBar</div>
    </div>
    <div class="bottom-tab-bar">
      <p>BottomTabBar Component Active</p>
    </div>
  </div>
  <footer>
    <p>Powered by AGRI-OS - Dark Industrial Operations (Mission Control)</p>
  </footer>
</body>
</html>`);
    return;
  }

  // SPA fallback: serve root HTML for non-API GET paths
  if (method === 'GET' && !url.startsWith('/api/')) {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(`<!DOCTYPE html>
<html>
<head>
  <title>AGRI-OS</title>
  <style>
    body {
      font-family: JetBrains Mono, monospace;
      background-color: #0D1117;
      color: #39D353;
      margin: 0;
      padding: 20px;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      flex: 1;
    }
    header {
      background-color: #0D1117;
      padding: 1rem;
      border-bottom: 1px solid #39D353;
    }
    .component-list {
      margin: 1rem 0;
    }
    .component-item {
      padding: 0.5rem;
      margin: 0.25rem 0;
      background-color: #161B22;
      border-radius: 4px;
    }
    .status-indicator {
      color: #39D353;
      font-weight: bold;
    }
  </style>
</head>
<body>
  <header>
    <h1>AGRI-OS - Dark Industrial Operations (Mission Control)</h1>
    <div class="status-indicator">System Operational</div>
  </header>
  <div class="container">
    <h2>Farm Status Overview</h2>
    <div class="component-list">
      <h3>Active Components:</h3>
      <div class="component-item">1</div>
      <div class="component-item">2</div>
      <div class="component-item">3</div>
      <div class="component-item">4</div>
      <div class="component-item">FieldZoneMap</div>
      <div class="component-item">AgentActivityFeed</div>
      <div class="component-item">FarmStatusOverview</div>
      <div class="component-item">BottomTabBar</div>
    </div>
    <div class="bottom-tab-bar">
      <p>BottomTabBar Component Active</p>
    </div>
  </div>
  <footer>
    <p>Powered by AGRI-OS - Dark Industrial Operations (Mission Control)</p>
  </footer>
</body>
</html>`);
    return;
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not found' }));
});

server.listen(8080, '0.0.0.0', () => {
  console.log('[runtime-server] NemoClaw-agritwin-dairy-agentic-ai-platform-frontend listening on 0.0.0.0:8080');
  console.log('[runtime-server] App loaded:', loaded);
  if (loadError) console.log('[runtime-server] Load error:', loadError);
});

// Keep the process alive even if the app module does not start a server.
setInterval(() => {}, 60 * 60 * 1000);
