// AIAssistantPanel page
// Generated by AgriTwin Agent Factory

import { AgentRecommendation } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function AIAssistantPanel() {
  return {
    page: 'AIAssistantPanel',
    entity: AgentRecommendation.name,
  };
}

export default AIAssistantPanel;
