// AlertsPanel page
// Generated by AgriTwin Agent Factory

import { HealthAlert } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function AlertsPanel() {
  return {
    page: 'AlertsPanel',
    entity: HealthAlert.name,
  };
}

export default AlertsPanel;
