// CowDetails page
// Generated by AgriTwin Agent Factory

import { Cow, Sensor, MilkYield } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function CowDetails() {
  return {
    page: 'CowDetails',
    entities: [Cow.name, Sensor.name, MilkYield.name],
  };
}

export default CowDetails;
