// FarmDashboard page
// Generated by AgriTwin Agent Factory

import { Herd, Cow } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function FarmDashboard() {
  return {
    page: 'FarmDashboard',
    entities: [Herd.name, Cow.name],
  };
}

export default FarmDashboard;
