// HerdTable page
// Generated by AgriTwin Agent Factory

import { Herd, Cow } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function HerdTable() {
  return {
    page: 'HerdTable',
    entities: [Herd.name, Cow.name],
  };
}

export default HerdTable;
