// NemoClaw-agritwin-dairy-agentic-ai-platform-frontend — Frontend entry point
// Generated by AgriTwin Agent Factory

import { entities } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export const app = {
  name: 'NemoClaw-agritwin-dairy-agentic-ai-platform-frontend',
  type: 'frontend',
  modules: ["dashboard","analytics","recommendations"],
  entityCount: entities.length,
};

export default app;
